name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.NAIROLF32_METRICS }}
          config_timezone: Africa/Porto-Novo
          filename: github-metrics.svg
          config_display: columns
          optimize: svg, css, xml
          experimental_features: --optimize-svg
          
          base: header, activity, community, repositories, metadata
          
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          
          plugin_habits: yes
          plugin_habits_facts: yes
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          
          plugin_anilist: yes
          plugin_anilist_user: nairolf32
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          
          plugin_music: yes
          plugin_music_token: ${{ secrets.SPOTIFY_SECRET }}
          plugin_music_mode: recent
          plugin_music_provider: spotify
          plugin_music_user: nairolf32

