name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.NAIROLF32_METRICS }}
          config_timezone: Africa/Porto-Novo
          template: markdown
          markdown: >-
            template.md
          filename: README.md
          config_output: markdown
          markdown_cache: .cache
          base: header, activity, community, repositories, metadata
          base_indepth: yes

          plugin_anilist: yes
          plugin_anilist_user: nairolf32
          plugin_anilist_sections: characters

          plugin_music: yes
          plugin_music_token: ${{ secrets.SPOTIFY_SECRET }}
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_user: nairolf32
